name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: test-cluster
  GKE_ZONE: us-east1
  DEPLOYMENT_NAME: api.yaml
  IMAGE: fiap-postech-coffee-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/819085636852/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider"
          service_account: "github-actions-service-account@postech-417415.iam.gserviceaccount.com"
